In [26]:
import numpy as np
from PIL import Image # for reading image files
from colorthief import ColorThief
import math

In [3]:
img_open = Image.open('yummy_macarons.jpg')
img = np.array(img_open)

In [4]:
np.unique(img, return_counts=True)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [5]:
img.shape

(533, 799, 3)

In [6]:
img_array = img.copy()
img_array.shape = ((img_array.shape[0] * img_array.shape[1]),img_array.shape[2],)
img_array.shape

(425867, 3)

In [7]:
np.unique(img_array, return_counts=True, axis=0)

(array([[  0,   0,   0],
        [  0,   0,   2],
        [  0,   0,   4],
        ...,
        [255, 254, 226],
        [255, 254, 230],
        [255, 255, 218]], dtype=uint8),
 array([17,  4,  1, ...,  1,  1,  3]))

In [8]:
col_values, col_counts = np.unique(img_array, return_counts=True, axis=0)
#value_and_count = [(value, count) for value, count in np.unique(img_array, return_counts=True, axis=0)]
col_values[0]

array([0, 0, 0], dtype=uint8)

In [9]:
if len(col_values)==len(col_counts):
    value_and_count = [(col_values[i], col_counts[i]) for i in range(len(col_values))]

In [10]:
value_and_count.sort(key = lambda x : x[1])
value_and_count

[(array([0, 0, 4], dtype=uint8), 1),
 (array([0, 0, 9], dtype=uint8), 1),
 (array([0, 2, 7], dtype=uint8), 1),
 (array([0, 6, 7], dtype=uint8), 1),
 (array([0, 8, 6], dtype=uint8), 1),
 (array([ 0,  8, 41], dtype=uint8), 1),
 (array([ 0, 11, 20], dtype=uint8), 1),
 (array([ 0, 11, 21], dtype=uint8), 1),
 (array([ 0, 12,  6], dtype=uint8), 1),
 (array([ 0, 13,  0], dtype=uint8), 1),
 (array([ 0, 15, 17], dtype=uint8), 1),
 (array([ 0, 16,  3], dtype=uint8), 1),
 (array([ 0, 16, 19], dtype=uint8), 1),
 (array([ 0, 17, 17], dtype=uint8), 1),
 (array([ 0, 18, 19], dtype=uint8), 1),
 (array([ 0, 18, 28], dtype=uint8), 1),
 (array([ 0, 19, 22], dtype=uint8), 1),
 (array([ 0, 19, 25], dtype=uint8), 1),
 (array([ 0, 20,  3], dtype=uint8), 1),
 (array([ 0, 20, 11], dtype=uint8), 1),
 (array([ 0, 20, 27], dtype=uint8), 1),
 (array([ 0, 20, 29], dtype=uint8), 1),
 (array([ 0, 20, 31], dtype=uint8), 1),
 (array([ 0, 21, 17], dtype=uint8), 1),
 (array([ 0, 22, 22], dtype=uint8), 1),
 (array([ 0, 23

In [11]:
most_pop_colors = value_and_count[::-1]
most_pop_colors[:10]

[(array([3, 1, 4], dtype=uint8), 909),
 (array([4, 2, 5], dtype=uint8), 908),
 (array([32,  8, 21], dtype=uint8), 512),
 (array([23,  6, 14], dtype=uint8), 493),
 (array([26,  6, 15], dtype=uint8), 460),
 (array([32,  9, 19], dtype=uint8), 443),
 (array([27,  7, 16], dtype=uint8), 405),
 (array([ 7,  6, 14], dtype=uint8), 399),
 (array([22,  5, 15], dtype=uint8), 396),
 (array([13, 10, 19], dtype=uint8), 391)]

In [12]:
mpc2 = value_and_count[-10:][::-1]
mpc2

[(array([3, 1, 4], dtype=uint8), 909),
 (array([4, 2, 5], dtype=uint8), 908),
 (array([32,  8, 21], dtype=uint8), 512),
 (array([23,  6, 14], dtype=uint8), 493),
 (array([26,  6, 15], dtype=uint8), 460),
 (array([32,  9, 19], dtype=uint8), 443),
 (array([27,  7, 16], dtype=uint8), 405),
 (array([ 7,  6, 14], dtype=uint8), 399),
 (array([22,  5, 15], dtype=uint8), 396),
 (array([13, 10, 19], dtype=uint8), 391)]

In [13]:
# via https://www.codespeedy.com/convert-rgb-to-hex-color-code-in-python/
def rgb_to_hex(rgb):
    r,g,b = rgb[:3]
    return '#%02x%02x%02x' % (r,g,b)

In [14]:
rgb_to_hex(most_pop_colors[0][0])

'#030104'

In [15]:
#%pip install colorthief

In [16]:
cfi = ColorThief('yummy_macarons.jpg')
color_list = cfi.get_palette(color_count=11)
color_list

[(34, 36, 34),
 (237, 210, 180),
 (216, 153, 78),
 (150, 46, 26),
 (119, 117, 77),
 (242, 207, 119),
 (216, 177, 140),
 (179, 90, 35),
 (69, 149, 121),
 (191, 119, 19)]

In [17]:
cl_hex = [rgb_to_hex(clr) for clr in color_list]
cl_hex

['#222422',
 '#edd2b4',
 '#d8994e',
 '#962e1a',
 '#77754d',
 '#f2cf77',
 '#d8b18c',
 '#b35a23',
 '#459579',
 '#bf7713']

In [18]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [19]:
sop = sum([x[1] for x in value_and_count])
sop

425867

In [20]:
sop == (img.shape[0] * img.shape[1])

True

In [21]:
based = np.unique(img_array, return_counts=True, axis=0)
vac2 = list(zip(based[0], based[1]))
vac2

[(array([0, 0, 0], dtype=uint8), 17),
 (array([0, 0, 2], dtype=uint8), 4),
 (array([0, 0, 4], dtype=uint8), 1),
 (array([0, 0, 9], dtype=uint8), 1),
 (array([0, 1, 3], dtype=uint8), 2),
 (array([0, 2, 7], dtype=uint8), 1),
 (array([0, 6, 7], dtype=uint8), 1),
 (array([0, 8, 6], dtype=uint8), 1),
 (array([ 0,  8, 41], dtype=uint8), 1),
 (array([ 0, 11, 20], dtype=uint8), 1),
 (array([ 0, 11, 21], dtype=uint8), 1),
 (array([ 0, 12,  6], dtype=uint8), 1),
 (array([ 0, 13,  0], dtype=uint8), 1),
 (array([ 0, 15, 17], dtype=uint8), 1),
 (array([ 0, 15, 19], dtype=uint8), 2),
 (array([ 0, 16,  3], dtype=uint8), 1),
 (array([ 0, 16, 19], dtype=uint8), 1),
 (array([ 0, 17, 17], dtype=uint8), 1),
 (array([ 0, 18, 19], dtype=uint8), 1),
 (array([ 0, 18, 28], dtype=uint8), 1),
 (array([ 0, 19, 17], dtype=uint8), 2),
 (array([ 0, 19, 20], dtype=uint8), 2),
 (array([ 0, 19, 22], dtype=uint8), 1),
 (array([ 0, 19, 25], dtype=uint8), 1),
 (array([ 0, 20,  3], dtype=uint8), 1),
 (array([ 0, 20, 11], d

In [22]:
help(zip)

Help on class zip in module builtins:

class zip(object)
 |  zip(*iterables) --> A zip object yielding tuples until an input is exhausted.
 |  
 |     >>> list(zip('abcdefg', range(3), range(4)))
 |     [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]
 |  
 |  The zip object yields n-length tuples, where n is the number of iterables
 |  passed as positional arguments to zip().  The i-th element in every tuple
 |  comes from the i-th iterable argument to zip().  This continues until the
 |  shortest argument is exhausted.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and ret

In [23]:
yeti = np.array(Image.open('yeti.png'))
yeti.shape

yeti_copy = yeti.copy()
yeti_copy.shape = ((yeti_copy.shape[0] * yeti_copy.shape[1]), yeti_copy.shape[2],)
based = np.unique(yeti_copy, return_counts=True, axis=0)
yeti_vac = list(zip(based[0], based[1]))
yeti_vac.sort(key = lambda x : x[1])

yeti_mpc = yeti_vac[-10:][::-1]
yeti_mpc

[(array([253, 253, 253, 255], dtype=uint8), 241),
 (array([255, 255, 255, 255], dtype=uint8), 198),
 (array([254, 254, 254, 255], dtype=uint8), 175),
 (array([252, 252, 252, 255], dtype=uint8), 122),
 (array([128, 123, 119, 255], dtype=uint8), 57),
 (array([127, 122, 118, 255], dtype=uint8), 55),
 (array([124, 119, 115, 255], dtype=uint8), 54),
 (array([130, 125, 121, 255], dtype=uint8), 52),
 (array([129, 124, 120, 255], dtype=uint8), 51),
 (array([125, 120, 116, 255], dtype=uint8), 51)]

In [24]:
yeti_hex = [(rgb_to_hex(ympc[0]), ympc[1]) for ympc in yeti_mpc]
yeti_hex

[('#fdfdfd', 241),
 ('#ffffff', 198),
 ('#fefefe', 175),
 ('#fcfcfc', 122),
 ('#807b77', 57),
 ('#7f7a76', 55),
 ('#7c7773', 54),
 ('#827d79', 52),
 ('#817c78', 51),
 ('#7d7874', 51)]

In [29]:
def col_dist(rgb1, rgb2):
    r1,g1,b1 = rgb1[:3]
    r2,g2,b2 = rgb2[:3]
    dis = pow(abs(r1 - r2),2) + pow(abs(g1 - g2),2) + pow(abs(b1 - b2),2)
    return math.sqrt(dis)